### ISSUE TITLE
Any html content inside slide

### ISSUE THREAD

**Issue by sagarbhosale91** [Wlada/angular-carousel-3d#9]
I dont want to use image in carousel..

**Comment by Wlada** [comment]
What would you use then ? You want to have some html content inside slide without image?

**Comment by sagarbhosale91** [comment]
Yes i want to use Html content only... not an image... if i remove sourceProp from source i get error like "Problem loading ....."

**Comment by Wlada** [comment]
Hi @sagarbhosale91 

At the moment is not possible. I'm planing some refactoring to allow users to put any html inside slide.
Expecting to finish that in about 1 month, but for now is not possible.

I will edit your question and transfer to enhancement.

Feel free to contribute if you have ideas.

**Comment by ErickRuano** [comment]
Hey @sagarbhosale91,

I stumbled upon the same need as you, so I added html support for it. It's not 100% clean but it should work for you, please find this version at https://github.com/ErickRuano/angular-carousel-3d

@Wlada I would gladly point out exactly what I did, very few changes actually, so you can help me clean it up and hopefully merge the branches.

Kind regards and thank you very much for this awesome work!

**Comment by Wlada** [comment]
Hi @ErickRuano 

Yes, that sounds great! Can you point what you changed ?

I had some Idea to allow users to put their ng-repeat and to create slides with any html elements.  On other side it will require directive transclude and little more html inside view. 

Maybe your idea is better. Please attach comment when you find time. 

New working week started and I'm a bit in chaos after holidays, but I will find time so we can implement good solution and to merge branches. 

Thanks for your effort!

**Comment by ErickRuano** [comment]
What I did today basically adds support for a "html" property to the options object.

If set to true, it will switch the ng-repeat on the directive for a new one which renders whichever stringified html any index/object has on its 'html' property, and compiles it.

Setting html to true also prevents the preloading images process.

The downside of this method is that you have to pass your template to each of the slides, but I also wanted to add an extra step in which if you pass a string instead of a bool to the "html" property it will take it as the default template.

Since it already compiles the html and its already inside any ng-repeat, you could do something like:

```
slides = [ { html : '<a href="{{slide.link}}">{{slide.link}}</a>', link : 'http://www.google.com' } ];
```

And each slide would render a link to its corresponding url.

Changes in src/ code can be easily read here:
https://github.com/ErickRuano/angular-carousel-3d/commit/01ba1934c619c30c5bac1ff0e41f9d1e78c21715

**Comment by sagarbhosale91** [comment]
Thanks a lot both of you for valuable support  !!!!!

One more feature I am waiting for.
Is there any arrow functionality in current slider.
I want to change slides using next/prev arrows.

**Comment by Wlada** [comment]
Hi @ErickRuano 

I made some changes on html slide logic. For me is much cleaner like this. Do you want to check. I would love to hear your opinion. 

Thanks
